name: Validate main source branch

on:
  pull_request:
    branches:
      - main

jobs:
  validate-source-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Allow only develop into main
        run: |
          if [ "${{ github.head_ref }}" != "develop" ]; then
            echo "A branch main só pode receber PR vindo da develop."
            echo "Branch atual: ${{ github.head_ref }}"
            exit 1
          fi